### PR TITLE
fix: validation_receipts scenario gets stuck

### LINKED ISSUE #329: `validation_receipts` scenario gets stuck in infinite doesn't end
Due to this loop in the scenario:

https://github.com/holochain/wind-tunnel/blob/2a46efdbbfef6a82d8408b64a43f2d06303ca01c/scenarios/validation_receipts/src/main.rs#L81

If validation doesn't finish for one agent then it never exits and thus the scenario runs forever.

This could be cause by not running on enough nodes. Currently, we run 2 nodes, each with 5 conductors and 1 agent on each conductor. Start by using 5+ nodes, each with one conductor.

AC:

- [ ] Add more Nomad client nodes to run the scenario
- [ ] Reduce the number of agents/conductors running on each node
- [ ] Fix the scenario so it works if the above doesn't fix it

### PR DESCRIPTION
**Pull request by veeso**
### Summary

Refactored the scenario logic in order to prevent concurrent actions to not being validated due to creation failed.

closes #329

### TODO:

- [x] All code changes are reflected in docs, including module-level docs
- [x] I ran the Nomad CI workflow successfully on my branch

## Summary by CodeRabbit

* **New Features**
  * Added a validation_receipts scenario and included it in the CI run matrix to expand automated coverage.

* **Chores**
  * Reworked validation receipt tracking and completion monitoring for scenarios.
  * Updated workspace dependencies for the new scenario.
  * Added ignore rules for the Rust rover project.
  * Minor formatting and whitespace cleanups across scenario configuration files.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: scenarios/validation_receipts/src/main.rs [hunk 1]
```diff
@@ -61,84 +58,100 @@ fn agent_setup(
...
+    // keep checking until all receipts are complete
+    while !ctx.get().scenario_values.is_action_complete() {
+        let response: Vec<ValidationReceiptSet> = call_zome(
+            ctx,
+            "crud",
+            "get_sample_entry_validation_receipts",
+            action_hash.clone(),
+        )?;
+
+        if started_at.elapsed() > Duration::from_secs(60) {
```
Comment (mattyg) [inline scenarios/validation_receipts/src/main.rs]: If we do want to keep the while loop in place, then this check should probably be before fetching the response or after processing it. Why fetch the response and wait for it if we're just going to drop it afterwards?
